version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: education_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  airflow-webserver:
    image: apache/airflow:2.7.3
    container_name: airflow_webserver
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres_container:5432/education_db
      - AIRFLOW__CORE__FERNET_KEY=NsbKP426yXjOu4PGs-gbcCudyZjbMCLdBCRxun6oahw=
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: webserver
    depends_on:
      - postgres

  airflow-scheduler:
    image: apache/airflow:2.7.3
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-webserver
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres_container:5432/education_db
      - AIRFLOW__CORE__FERNET_KEY=NsbKP426yXjOu4PGs-gbcCudyZjbMCLdBCRxun6oahw=
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler